// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ContourContext))]
    partial class ContourContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("DataAccess.ContourEntity", b =>
                {
                    b.Property<Guid>("ContourEntityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DicomId");

                    b.Property<bool>("IsManual");

                    b.Property<string>("Tag");

                    b.HasKey("ContourEntityId");

                    b.ToTable("Contours");
                });
#pragma warning restore 612, 618
        }
    }
}
